name: "Playwright Tests"
description: "Run E2E tests with Playwright"

runs:
  using: "composite"
  steps:
    - name: Install Playwright Browsers
      shell: bash
      run: yarn playwright install --with-deps
    - name: Run Playwright tests
      shell: bash
      run: yarn playwright test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
