name: verify

on:
  pull_request:
    branches: [main]

jobs:
  verify:
    runs-on: ubuntu-latest
    name: Build and Test
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"

      - uses: ./.github/workflows/yarn-install.yml

      - name: Build
        run: yarn build

      - name: Test
        run: yarn test
